# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec for the LaserTrace Pro desktop app (Windows .exe / macOS .app).

Built as a **onedir** bundle, not onefile: with PySide6 + OpenCV + SciPy the
archive is large enough that onefile's extract-to-temp costs ten seconds on
every launch, and antivirus tools treat self-extracting binaries with more
suspicion. Windows ships as a folder to unzip; on macOS the folder *is* the
.app, so it looks like one icon either way.

    pyinstaller packaging/lasertrace.spec --noconfirm

Data files matter here for the same reason they mattered for the wheel: the
built-in presets and the window icon are loaded by path at runtime, and
`Path(__file__).parent` inside a frozen module resolves under sys._MEIPASS —
so they must be laid down at the same relative paths they occupy in the source
tree. tools/verify_bundle.py checks that they actually were.
"""
import sys
from pathlib import Path

ROOT = Path(SPECPATH).resolve().parent
NAME = "LaserTrace Pro" if sys.platform == "darwin" else "LaserTracePro"

datas = [
    (str(ROOT / "lasertrace" / "preset_data"), "lasertrace/preset_data"),
    (str(ROOT / "lasertrace_ui" / "assets"), "lasertrace_ui/assets"),
]

# The macOS icon is generated by `iconutil` at build time (see the workflow);
# fall back gracefully so the spec still runs on a bare checkout.
_icns = ROOT / "packaging" / "icon.icns"
_ico = ROOT / "lasertrace_ui" / "assets" / "icon.ico"
ICON = str(_icns) if (sys.platform == "darwin" and _icns.exists()) else (
    str(_ico) if sys.platform != "darwin" and _ico.exists() else None)

hiddenimports = [
    "scipy.fft",
    "skimage.morphology",
    "shapely.geometry", "shapely.ops", "shapely.strtree", "shapely.validation",
    "ezdxf.math",
    "pypdfium2",
]

# Nothing in the app touches these; excluding them saves a few hundred MB and
# stops PyInstaller dragging in a second GUI toolkit.
# NOTE: do NOT exclude `unittest`. ezdxf -> pyparsing imports pyparsing.testing
# at module load, which imports unittest, so excluding it makes every DXF
# export crash - i.e. the whole point of the app. tools/verify_bundle.py
# catches this by actually exporting a file.
excludes = [
    "matplotlib", "tkinter", "pytest", "_pytest",
    "IPython", "notebook", "jupyter", "sphinx",
    "PyQt5", "PyQt6", "PySide2", "wx",
    "PySide6.QtWebEngineCore", "PySide6.QtWebEngineWidgets", "PySide6.QtQuick",
    "PySide6.QtQml", "PySide6.Qt3DCore", "PySide6.QtMultimedia",
    "PySide6.QtCharts", "PySide6.QtDataVisualization", "PySide6.QtBluetooth",
    "PySide6.QtNetwork", "PySide6.QtPositioning", "PySide6.QtSql",
    "PySide6.QtTest", "PySide6.QtDesigner",
]

a = Analysis(
    [str(ROOT / "lasertrace_ui" / "main.py")],
    pathex=[str(ROOT)],
    binaries=[],
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=excludes,
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name=NAME,
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,                 # UPX trips antivirus heuristics for no real win
    console=False,             # windowed app; the CLI is the `lasertrace` wheel
    disable_windowed_traceback=False,
    # argv_emulation pumps AppleEvents at startup and has been known to hang a
    # headless launch - which is exactly how CI verifies the build. Files are
    # opened from inside the app instead.
    argv_emulation=False,
    target_arch=None,          # follows the building interpreter's arch
    codesign_identity=None,
    entitlements_file=None,
    icon=ICON,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name=NAME,
)

if sys.platform == "darwin":
    app = BUNDLE(
        coll,
        name=f"{NAME}.app",
        icon=ICON,
        bundle_identifier="com.juicedsystems.lasertracepro",
        info_plist={
            "CFBundleShortVersionString": "0.1.1",
            "CFBundleVersion": "0.1.1",
            "NSHighResolutionCapable": True,
            "LSMinimumSystemVersion": "11.0",
            "NSHumanReadableCopyright": "Copyright (c) 2026 Juiced Systems. MIT licensed.",
            "CFBundleDocumentTypes": [
                {
                    "CFBundleTypeName": "Artwork",
                    "CFBundleTypeRole": "Viewer",
                    "LSItemContentTypes": [
                        "public.png", "public.jpeg", "public.tiff",
                        "com.compuserve.gif", "com.adobe.pdf", "public.svg-image",
                    ],
                }
            ],
        },
    )
